name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Install WRK
      run: sudo apt-get install wrk
    - name: Run server
      id:   run_perf
      shell: bash
      run: cargo run -- ./point.sqlite &
           sleep 5 &&
           perf=$(wrk -t12 -c100 -d30 http://localhost:4000/user/example@lunaris.jp/balance) &&
           echo echo "{perf_out}={perf}" >> $GITHUB_OUTPUT


    - name: Auto Comment
      run: |
          curl \
            -X POST \
            ${{ github.event.issue.comments_url }} \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }} \
            --data '{ "body": "Performance metrics for this code are: ${{ steps.run_perf.outputs.perf_out }}" }'
